version: "3.6"

services:
  vpn:
    # restart: always
    # entrypoint: ["/sbin/tini", "--", "/usr/bin/openvpn.sh"]
    # command: '-p "49150" -p "49150;udp"'
    # tty: true

  api:
    links:
      - vpn:transmission
      - vpn:jackett
    networks:
      - default

  jackett:
    network_mode: "service:vpn"
    depends_on:
      - vpn

  transmission:
    network_mode: "service:vpn"
    depends_on:
      - vpn
